### ISSUE TITLE
Can you add possibility to add custom server too?

### ISSUE THREAD

**Issue by mannaggacardarell** [kishikawakatsumi/among-us-server-status#1]
Can you add possibility to add custom server too?

And how i can add this to discord?

**Comment by kishikawakatsumi** [comment]
> And how i can add this to discord?

The `/discord-embed` endpoint will return JSON that can be posted to Discord as-is. Then you just write your own Discord bot like the following:

```js
const express = require('express')
const app = express()

app.get('/', (request, response) => {
  response.send('Glitch woke up')
})

const listener = app.listen(process.env.PORT, () => {
  console.log('Your app is listening on port ' + listener.address().port)
})

const Discord = require('discord.js')
const client = new Discord.Client()
const axios = require('axios').default

client.on('ready', () => {
  console.log(`Logged in as ${client.user.tag}!`)
})

client.on('message', async msg => {
  if (msg.content === 'auserver') {
    const response = await axios.get(
      'https://among-us-server-status.herokuapp.com/discord-embed'
    )
    msg.channel.send(response.data)
  }
})

client.login(process.env.DISCORD_BOT_TOKEN)
```

> Can you add possibility to add custom server too?

 I am not familiar with custom server. Is there a custom server that is so active that you want to know about the crowding?

**Comment by mannaggacardarell** [comment]
There are many servers, they are all based on impostor server projet: https://github.com/Impostor/Impostor

One of the most "famous" is from cheep-yt. But, for example, i have one with detective mode active

**Comment by kishikawakatsumi** [comment]
I'm not sure, but if they return the same packets as Among Us official server, I think it's possible to modify it to get your expected results. I don't use any custom server so I don't have a plan to support that feature on my website.
